version: '3.1'

services:
  db:
    image: 'postgres:15.3'
    container_name: magic-post-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: magic-post
    ports:
      - "5432:5432"