# get git information: http://localhost:8080/actuator/info
management:
  info:
    git:
      mode: full

server:
  port: 8090
  servlet:
    context-path: /magic-post

spring:
  datasource:
    host: localhost
    port: 5433
    dbname: magic-post
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbname}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      pool-name: SpringBootJPAHikariCP
      connection-timeout: 3000
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-test-query: select 1
      connection-init-sql: select 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 400
          lob:
            non_contextual_creation: true
        default_schema: magic-post
        ddl-auto: validate
    generate-ddl: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: ["location"]
    locations: classpath:/db/migration

  docker:
    compose:
      enabled: true
      file: src/main/docker/docker-compose.yml
      lifecycle-management: start_and_stop
